### ISSUE TITLE
Cherry pick the DataLink code

### ISSUE THREAD

**Issue by shadowbq** [pcaprub/pcaprub#34]
162c5ba426d07142d3d0f467eff9ac7514e5b683 - Add support for setting PCAP datalink type.

**Comment by crondaemon** [comment]
Ping.

**Comment by shadowbq** [comment]
@crondaemon merge the three branches it into master if it's working, bump the version and lets push.

**Comment by crondaemon** [comment]
Can't merge this. Tests don't pass, I don't know if it's due to the current code, or it was already present. I'll take a look and merge if I-m able to fix it.

**Comment by crondaemon** [comment]
Pushed a new commit that fixes the tests, then merged. Gem can't be pushed by me on rubygems.
