### ISSUE TITLE
Cherry pick the pcap_compile and fix pcap_freecode

### ISSUE THREAD

**Issue by shadowbq** [pcaprub/pcaprub#35]
We should allow for bpf filter tests as this would increase the usefulness of the library as a whole.

See 68678c9904bb1aba3d90f7fcde866f2ff9061bc6 - Exposes the #compile method from bpf lib.

But... the coder didnt expose pcap_freecode(). We would need to do that as well.. cleanly. Possibly automatically after the pcap_compile call as this type of call (garbage collection) is not that rubyish.

**Comment by crondaemon** [comment]
Ping.

**Comment by crondaemon** [comment]
Merged.
