### ISSUE TITLE
Rake task to 'release' does not work.

### ISSUE THREAD

**Issue by shadowbq** [pcaprub/pcaprub#36]
Overide the rubygems-task method that requires a .gemspec file. We dont have or need a spec file as we attempt to cross compile and spec mess that up.

Steps that needed to be performed with releasing..

```shell
git tag -a v0.12.0 -m 'version 0.12.0' a38c6ee5e6cc5f4d18a72c0bb399522bbc76c897
git push origin v0.12.0
bundle exec rake clobber
bundle exec rake compile
gem push pkg/pcaprub-0.12.0.gem 
   ${username} / ${password}
```

**Comment by crondaemon** [comment]
Ping.

**Comment by crondaemon** [comment]
Merged.

**Comment by shadowbq** [comment]
great. We should release very soon.

**Comment by shadowbq** [comment]
missing step after compile
`bundle exec rake package`
