### ISSUE TITLE
filter not working as expected

### ISSUE THREAD

**Issue by lnxbil** [pcaprub/pcaprub#39]
Hi,

I'm struggling with a strange problem. I have a filter rule which works in `tcpdump` yet not in `pcaprub`:

``` ruby
#!/usr/bin/env pry

require 'pcaprub'

capture = ::Pcap.open_live("eth0", 65535, true, 0)
capture.setfilter 'tcp and dst port 22 and (tcp[tcpflags] & tcp-syn != 0) and (tcp[tcpflags] & tcp-ack == 0)'
# also not working
# capture.setfilter 'tcp and dst port 22 and (tcp[tcpflags] & tcp-syn != 0)'
# this actually works
#capture.setfilter 'tcp and dst port 22'

capture.each_packet do |pkt|
    p pkt
    binding.pry
end
```

Here the session information

```
Exception: Interrupt:
--
From: (pry) @ line 10 @ level: 0 of backtrace (of 20).

     5: capture = ::Pcap.open_live("eth0", 65535, true, 0)
     6: capture.setfilter 'tcp and dst port 22 and (tcp[tcpflags] & tcp-syn != 0) and (tcp[tcpflags] & tcp-ack == 0)'
     7: #capture.setfilter 'tcp and dst port 22 and (tcp[tcpflags] & tcp-syn != 0)'
     8: #capture.setfilter 'tcp and dst port 22'
     9:
 => 10: capture.each_packet do |pkt|
    11:     p pkt
    12:     binding.pry
    13: end
...exception encountered, going interactive!
[11] pry(main)> capture.stats
=> {"recv"=>4, "drop"=>4, "idrop"=>0}
[12] pry(main)> exit
```

Any ideas?

**Comment by shadowbq** [comment]
Is this raising an Error? or silently not filtering packets? what is the behavior you are observing?

**Comment by lnxbil** [comment]
It is silently not filtering any packets. If i omit the filter rule, I receive packets.

**Comment by shadowbq** [comment]
So it is filtering packets? Just all of them?

**Comment by lnxbil** [comment]
the packages are dropped. If I filter myself using ruby code inside the loop it works as expected. I do not know why the mentioned filter is not working in the ruby library, whereas it is actually working in tcpdump itself.

**Comment by shadowbq** [comment]
So appears to compile this string.. maybe we are not escaping something here.

```
~/sandbox/pcaprub)$ pry
[1] pry(main)> require 'pcaprub'
=> true
[2] pry(main)> capture = PCAPRUB::Pcap.open_dead(Pcap::DLT_NULL, 65535)
=> #<PCAPRUB::Pcap:0x000000021fa958>
[3] pry(main)> capture.compile('tcp and dst port 22 and (tcp[tcpflags] & tcp-syn != 0)')
=> #<PCAPRUB::Pcap:0x000000021fa958>
```

**Comment by lnxbil** [comment]
Years later, I just rediscovered this library, ran into the same problem and was baffled about my own bug report. After three additional hours, I discovered the problem and it lies in the way i tested it. In my example, I want to act on one incoming packet and that is not captured - as described - but in fact it is. The buffer is too big and the time to wait is disabled (both default settings in the examples), so that the packet will reach the code, but only if the buffer is full or some internal timeout occurs (in minutes).

I tested with a simple `ssh <server> hostname` and it only generates a `pcap` file (with `tcpdump`) that is roughly 11k and the limit as described above (and the examples) are always 64k, so you need a lot of packages and/or a lot of time to get results. Just reducing the buffer to `512` does not yield any changes, only setting the timeout to `500` (in ms) will yield direct packet detection.

**Comment by crondaemon** [comment]
Glad you finally found the solution.
