### ISSUE TITLE
Please update rubygems.org gem file to 0.12.1

### ISSUE THREAD

**Issue by anthraxx** [pcaprub/pcaprub#42]
Hey,
If its possible, it would be awesome if you can update your gem stored on rubygems.org
the latest version there is 0.12.0: 
https://rubygems.org/gems/pcaprub/versions/0.12.0

cheers

**Comment by shadowbq** [comment]
0.12.1 pushed to ruby gems.

**Comment by anthraxx** [comment]
thank you very much :smile: :+1:
