### ISSUE TITLE
"Symbol not found: _pcap_lookupdev" error on Mac OS X El Capitan 

### ISSUE THREAD

**Issue by evilsocket** [pcaprub/pcaprub#46]
Hi guys, a few users of a project of mine reported this issue on Mac OS X El Capitan ( I'm using the same version and still I'm not able to reproduce it ):

    dyld: lazy symbol binding failed: Symbol not found: _pcap_lookupdev
    Referenced from: /Library/Ruby/Gems/2.0.0/gems/pcaprub-0.12.1/lib/pcaprub_c.bundle
    Expected in: flat namespace

    dyld: Symbol not found: _pcap_lookupdev
    Referenced from: /Library/Ruby/Gems/2.0.0/gems/pcaprub-0.12.1/lib/pcaprub_c.bundle
    Expected in: flat namespace

    Trace/BPT trap: 5

OS version:

    15.3.0 Darwin Kernel Version 15.3.0

Ruby version:

    ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

You'll find more details on the original issue located here https://github.com/evilsocket/bettercap/issues/182

Any idea why this is happening?

**Comment by shadowbq** [comment]
What version of libpcap are they using?

**Comment by evilsocket** [comment]
latest from brew ... I guess?

**Comment by shadowbq** [comment]
We are calling a flat namespace on 'pcap_lookupdev' from <pcap.h>  in https://github.com/pcaprub/pcaprub/blob/master/ext/pcaprub_c/pcaprub.c#L66

**Comment by shadowbq** [comment]
Looking into  
https://github.com/Homebrew/homebrew-dupes/blob/7d55768245819bc00455087647517d8f51afde6f/libpcap.rb

url "http://www.tcpdump.org/release/libpcap-1.7.4.tar.gz"

libpcap 1.7.4

https://github.com/the-tcpdump-group/libpcap/blob/6077117e557c2eb926f070c0d4851d24e557b3bc/inet.c

pcap_lookupdev is still in the flat namespace

https://github.com/the-tcpdump-group/libpcap/blob/6077117e557c2eb926f070c0d4851d24e557b3bc/pcap/pcap.h#L278

**Comment by shadowbq** [comment]
They installed this into system gems? 

There is a permissions problem, a path problem.

Would recommend rvm, brew and sudo.

**Comment by inmiscible** [comment]
hello,
I'll trying to respond y I don't understood all about you asking for, I have the libpcap installed with brew
brew install libpcap

==> Installing libpcap from homebrew/dupes
==> Downloading https://homebrew.bintray.com/bottles-dupes/libpcap-1.7.4.el_capitan.bottle.1.tar.gz
######################################################################## 100,0%
==> Pouring libpcap-1.7.4.el_capitan.bottle.1.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

LDFLAGS:  -L/usr/local/opt/libpcap/lib
CPPFLAGS: -I/usr/local/opt/libpcap/include

==> Summary
:beer: /usr/local/Cellar/libpcap/1.7.4: 98 files, 796.4K

I also can located pcap/pcap.h on the system :
/opt/local/include/pcap/pcap.h
/opt/local/include/pcap.h

**Comment by inmiscible** [comment]
Solved! finally the problem was a permissions problem.

Thanks for your support.

**Comment by datascienceteam01** [comment]
"Solved! finally the problem was a permissions problem.

Thanks for your support."  and thank you for sharing (not!) what the permissions problem was.
