### ISSUE TITLE
gem install pcaprub does not work

### ISSUE THREAD

**Issue by AlGreed** [pcaprub/pcaprub#49]
Fetching: pcaprub-0.12.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing pcaprub:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20160522-30344-1gwjcsq.rb extconf.rb

[*] Running checks for pcaprub_c code...
platform is x86_64-linux-gnu
checking for ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl()... yes
checking for pcap_open_live() in -lpcap... no
checking for pcap_setnonblock() in -lpcap... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling pcaprub.c
pcaprub.c:11:18: fatal error: pcap.h: No such file or directory
compilation terminated.
Makefile:238: recipe for target 'pcaprub.o' failed
make: *** [pcaprub.o] Error 1

make failed, exit code 2

**Comment by crondaemon** [comment]
You have to install the development libpcap packages.
