### ISSUE TITLE
pcaprub

### ISSUE THREAD

**Issue by elswa770** [pcaprub/pcaprub#53]
gem install pcaprub -v '0.13.0'                 Building native extensions. This could take a while...                                              ERROR:  Error installing pcaprub:                         ERROR: Failed to build gem native extension.                                                                                                      current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0/ext/pcaprub_c                                          /data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/2.7.0 -r ./siteconf20200410-21338-99uysh.rb extconf.rb
                                                  [*] Running checks for pcaprub_c code...          platform is aarch64-linux-android                 checking for ruby/thread.h... yes                 checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl()... yes  checking for pcap_open_live() in -lpcap... no     checking for pcap_setnonblock() in -lpcap... no
creating Makefile                                 
current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0/ext/pcaprub_c                                              make "DESTDIR=" clean
                                                  current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0/ext/pcaprub_c
make "DESTDIR="
compiling pcaprub.c                               pcaprub.c:11:10: fatal error: 'pcap.h' file not found                                               #include <pcap.h>                                          ^~~~~~~~
1 error generated.                                make: *** [Makefile:245: pcaprub.o] Error 1                                                         make failed, exit code 2                          
Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0 for inspection.                            Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/extensions/aarch64-linux-android/2.7.0/pcaprub-0.13.0/gem_make.out

**Comment by crondaemon** [comment]
You don't have libpcap installed. Depending on your distribution you may need libpcap-dev, libpcap-devel or similar.
