### ISSUE TITLE
npcap support

### ISSUE THREAD

**Issue by kkzhang** [pcaprub/pcaprub#59]
WinCap is dead. As a alternative, npcap is still under active development. But when build with replaceing wincap_dev_dir with ncap sdk, errors shown:

`gem install pcaprub -- --with-pcap-dir="C:\npcap-sdk-1.11"`

```
current directory: C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pcaprub-0.12.4/ext/pcaprub_c
make DESTDIR\=
generating pcaprub_c-x64-mingw32.def
compiling pcaprub.c
pcaprub.c:13:10: fatal error: Win32-Extensions.h: No such file or directory
   13 | #include <Win32-Extensions.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:245：pcaprub.o] 错误 1
```

Of course that's not a bug, just a try. If npcap can be supported, that's awesome.

**Comment by adfoster-r7** [comment]
@crondaemon Is this issue free to look at? It looks like npcap should be backwards compatible, so it might be possible to support both winpcap and npcap transparently. We'd be happy to take a look at this if it hasn't already been investigated :+1:

**Comment by crondaemon** [comment]
Feel free to look into it, thanks.

**Comment by dwelch-r7** [comment]
Got a PR up here for adding npcap support https://github.com/pcaprub/pcaprub/pull/71
