### ISSUE TITLE
Release 0.13.2

### ISSUE THREAD

**Issue by adfoster-r7** [pcaprub/pcaprub#67]
Hi there; Thanks for the gem - I was just wondering when 0.13.2 would be released - I was hoping to pull in the work for supporting https://github.com/pcaprub/pcaprub/issues/62 / https://github.com/pcaprub/pcaprub/pull/64 for ucrt support

**Comment by adfoster-r7** [comment]
cc @crondaemon 🤞

**Comment by crondaemon** [comment]
Hi. I had no plans in releasing anything, since no relevant features popped up. By the way, since the repo is a bit stale, I am open for a new release that ships your changes.

**Comment by crondaemon** [comment]
Done.
